// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Exam_System.Models;

public partial class CourseTrack
{
    public int TrackId { get; set; }

    public int CourseId { get; set; }

    public virtual Course Course { get; set; }

    public virtual Track Track { get; set; }
}