// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Exam_System.Models
{
    public partial class GetAdminDataResult
    {
        public int AdminId { get; set; }
        public string AdminFName { get; set; }
        public string AdminLName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    }
}
