// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Exam_System.Models
{
    public partial class GetCourseDataResult
    {
        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public int? PassDegree { get; set; }
    }
}
