// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Exam_System.Models
{
    public partial class GetCourseTopicResult
    {
        public int TopicId { get; set; }
        public string TopicName { get; set; }
        public int? CourseId { get; set; }
    }
}
