// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Exam_System.Models
{
    public partial class GetInstrustureByIdResult
    {
        public int InstructorId { get; set; }
        public string InstructorFName { get; set; }
        public string InstructorLName { get; set; }
        [Column("InstructorSalary", TypeName = "decimal(10,2)")]
        public decimal? InstructorSalary { get; set; }
        public string InstructorEmail { get; set; }
        public string InstructorPassword { get; set; }
        public string InstructorGender { get; set; }
    }
}
