// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Exam_System.Models
{
    public partial class GetStudentDataResult
    {
        public int StudentId { get; set; }
        public string StudentFName { get; set; }
        public string StudentLName { get; set; }
        public string StudentEmail { get; set; }
        public string StudentGender { get; set; }
        public string StudentPassword { get; set; }
        public int? TrackId { get; set; }
    }
}
