// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Exam_System.Models
{
    public partial class SelectExamByIdResult
    {
        public int ExamId { get; set; }
        public DateOnly? ExamDate { get; set; }
        public TimeOnly? StartTime { get; set; }
        public TimeOnly? EndTime { get; set; }
        public TimeOnly? Duration { get; set; }
        public int? CourseId { get; set; }
        public int? TrackId { get; set; }
        public int? InstructorId { get; set; }
        public int? FullMark { get; set; }
    }
}
