// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Exam_System.Models
{
    public partial class SelectTrackByIdResult
    {
        public int TrackId { get; set; }
        public string TrackName { get; set; }
        public int? SupervisorId { get; set; }
        public int? Capacity { get; set; }
    }
}
