// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Exam_System.Models
{
    public partial class SelectAllStudentAnswersResult
    {
        public int StudentId { get; set; }
        public int ExamId { get; set; }
        public int QuestionId { get; set; }
        public int? AnswerChooseId { get; set; }
        public string StudentName { get; set; }
        public string QuestionBody { get; set; }
    }
}
