// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Exam_System.Models
{
    public partial class SelectAnswersByQuestionIDResult
    {
        public int AnswerId { get; set; }
        public int? AnswerNumber { get; set; }
        public string AnswerBody { get; set; }
        public bool? IsCorrect { get; set; }
        public int? QuestionId { get; set; }
    }
}
